### PR TITLE
fix ios crash while accessing available calendars

### PR DESCRIPTION
**Pull request by stonewoodman**
add missing request access to getAvailableCalendars on ios

### CODE REVIEW

**Review by bretislavstepan — APPROVED** [review]

**Comment by bretislavstepan** [comment]
@stonewoodman Thanks!

@Fir3st You know my current situation :-) I have only seen it on mobile phone... but it looks good.

**Comment by Fir3st** [comment]
@stonewoodman did you test it? Unfortunately, @bretislavstepan is the only team member who can test it (but he is currently unavailable). I can merge it and publish new version.

**Comment by stonewoodman** [comment]
@Fir3st yes i did test it on an physical iPhone device. I get a List with calendars, that are available. Without the fix, the app crashed (close instantly and in xcode log you can see a message, that no permission is set)

**Comment by stonewoodman** [comment]
@Fir3st @bretislavstepan 
I added a new commit. 
If you remove the right to access to calender for the app in ios system settings, then error is nil but accessGranted is false. I have additionally added the check for accessGranted.

**Comment by Fir3st** [comment]
@stonewoodman @bretislavstepan Ok merged and published.

**Pull request merged**
